-- CREATE DATABASE IF NOT EXISTS node;
-- USE node;

CREATE TABLE user (
	id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(50) UNIQUE,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);